### ISSUE TITLE
Add api endpoint for tars injection materials

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-metadata-service#166]
# User story
As a user, I want to retrieve information from TARS using a rest api, so I can easily get the data

# Acceptance criteria
- [x] Given the aind-metadata-service is running, when a user inputs a viral prep lot number, then Json response is returned
- [x] Given a response is returned, then the it will contain the serialized InjectionMaterials object
- [x] If there is an error retrieving data, then an error response is returned
- [x] If there is no data for the prep lot number, then a No Data Response is returned

# Sprint Ready Checklist 
- [x] 1. Acceptance criteria defined
- [x] 2. Team understands acceptance criteria
- [x] 3. Team has defined solution / steps to satisfy acceptance criteria
- [x] 4. Acceptance criteria is verifiable / testable
- [x] 5. External / 3rd Party dependencies identified
- [x] 6. Ticket is prioritized and sized

# Notes
For now, we can call the endpoint tars_injection_materials

**Comment by mekhlakapoor** [comment]
blank string -> no data response
get results + then filter equal + then map from there

**Comment by mekhlakapoor** [comment]
This ticket took longer than expected because the TARS API's search functionality supports "contains". Therefore, we needed to add a filter on the response to ensure that the service only maps injection_materials for prep lots that are an exact match. Also added a no data response class method to ModelResponse.
