### ISSUE TITLE
Incorrect source for mice not bred at Allen Institute

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-metadata-service#222]
**Describe the bug**
Mice sourced outside of Allen have incorrect breeding information.

**To Reproduce**
1. Go to ['mouse 714640'](http://aind-metadata-service/subject/714640)
2. See that source is Allen Institute instead of Jackson Laboratories

**Comment by mekhlakapoor** [comment]
Right now, the metadata-service assumes that all mice in Labtracks is from the Allen Institute. Source is not being tracked in a particular table/field; Instead, if a subject is not from AI, it is just noted in Comments. @saskiad @dyf Would it be best for the metadata-service to always return source as None instead of assuming it's from AI?

**Comment by mekhlakapoor** [comment]
Game plan:  Check if we can find breeding info. If that information exists, it is AI source. Otherwise, either map source to null or look in the comment.
