### ISSUE TITLE
Ghost procedures

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-metadata-service#282]
**Describe the bug**
I see a number of records where there is a LAS Surgery with a date, iacuc_protocol, and experimenter_full_name, and nothing else. What are these procedures? 

**To Reproduce**
1. Go to '...' metadata service
2. enter 708026 in procedures, hit search
3. the last procedures (2024-09-11) has no information

2. enter 655571 in procedures, hit search
3. last procedures has no information

Both of these have "LAS_XXXX" as the experimenter full name whereas the other LAS procedures (the Perfusion) only has a number for the name. That seems like it might be relevant

**Expected behavior**

I expect some sort of procedure name for a procedure - and ideally other relevant fields.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mekhlakapoor** [comment]
the LAS procedures (the Perfusion)that only has a number for the name is coming from Labtracks, while the ones with "LAS-XXXX" is coming from LAS's sharepoint. Right now, we are only mapping RO and IP injections from the LAS sharepoint, but these subjects have other non-surgical procedures which is why it's returning a ghost procedure. I can add a check to ensure it only returns the surgery if we have mapped procedures though
